[package]
name = "Interactive_Zero_Knowledge_Proof_of_Knowledge_of_Discrete_Log_Problem_Protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
rand = "0.8"